name: CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup files
        run: npm i
      - name: Run tests
        run: npm test
      - name: Prepare files for deployment
        run: |
          npm run build
          cp -R ./public ../
          rm -rf ./*
          cp -R ../public/* ./
      - name: Push to pages repo
        run: |
          git config --global user.name 'Automation'
          git config --global user.email 'palf1997@gmail.com'
          git stash
          git checkout -b pages
          git stash pop
          git add .
          git commit -m "Automated deploy"
          git push origin pages --force
