name: CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup files
        run: |
          npm i
          npm run build
          cp -R ./public ../
          rm -rf ./*
          cp -R ../public/* ./

      # Runs a set of commands using the runners shell
      - uses: actions/checkout@v2
      - name: Push to pages repo
        run: |
          git stash
          git checkout -b pages
          git commit -am "Automated deploy"
          git push --force
